[package]
name = "qctidy-analyzer"
description = "Circuit analysis and metrics for QCTidy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["science"]

[lib]
doctest = false

[dependencies]
qctidy = { path = "../library" }
qctidy-ports = { path = "../ports" }
serde = { workspace = true, features = ["derive"] }

[features]
default = ["analyzer"]
analyzer = []

[lints]
workspace = true
