[workspace]
members = [
    "crates/analyzer",
    "crates/cli",
    "crates/codegen",
    "crates/converter",
    "crates/estimator",
    "crates/facade",
    "crates/library",
    "crates/presenter",
    "crates/qiskit",
    "crates/server",
    "crates/storage",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
getset = "0.1.6"
inew = { git = "https://github.com/AnotherGoat/inew" }
num-rational = "0.4.2"
pyo3 = "0.28"
serde = "1"
serde_json = "1"
strum = "0.28.0"
strum_macros = "0.28.0"
thiserror = "2.0.18"
