[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files", args = ["--maxkb=1000"] },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/FeryET/pre-commit-rust"
rev = "v1.2.1"
hooks = [
  { id = "fmt" },
  { id = "cargo-check", args = ["--workspace"] },
  { id = "test" },
]
