[package]
name = "qsimplify-facade"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
qsimplify = { path = "../library" }
qsimplify-codegen = { path = "../codegen" }
qsimplify-converter = { path = "../converter" }
qsimplify-estimator = { path = "../estimator" }
qsimplify-ports = { path = "../ports" }
qsimplify-presenter = { path = "../presenter" }
qsimplify-storage = { path = "../storage" }
getset = { workspace = true }
inew = {workspace = true}

[lints]
workspace = true
