[package]
name = "qsimplify-facade"
version.workspace = true
edition.workspace = true

[dependencies]
qsimplify = { path = "../library" }
qsimplify-codegen = { path = "../codegen" }
qsimplify-converter = { path = "../converter" }
qsimplify-estimator = { path = "../estimator" }
qsimplify-presenter = { path = "../presenter" }
qsimplify-storage = { path = "../storage" }

[lints]
workspace = true
