[package]
name = "qctidy-facade"
description = "Facade for QCTidy client implementations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["science"]

[lib]
doctest = false

[dependencies]
qctidy = { path = "../library" }
qctidy-ports = { path = "../ports" }
getset = { workspace = true }
inew = { workspace = true }

[features]
default = [
    "analyzer",
    "codegen-qiskit",
    "codegen-openqasm3",
    "converter-cbor",
    "converter-json",
    "converter-msgpack",
    "converter-xml",
    "presenter-graphviz",
    "estimator",
]
analyzer = []
codegen-qiskit = []
codegen-openqasm3 = []
converter-cbor = []
converter-json = []
converter-msgpack = []
converter-xml = []
presenter-graphviz = []
estimator = []

[lints]
workspace = true
