[package]
name = "qsimplify-converter"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
qsimplify = { path = "../library" }
qsimplify-ports = { path = "../ports" }
quick-xml = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }

[lints]
workspace = true
