[package]
name = "qctidy-tui"
description = "Terminal user interface for QCTidy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["science", "command-line-utilities"]

[dependencies]
qctidy = { path = "../library" }
qctidy-converter = { path = "../converter" }
qctidy-ports = { path = "../ports" }
crossterm = { workspace = true }
fuzzy-matcher = { workspace = true }
ratatui = { workspace = true }

[lints]
workspace = true
