[package]
name = "qctidy-codegen"
description = "Code generator for QCTidy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["science", "encoding"]

[lib]
doctest = false

[dependencies]
qctidy = { path = "../library" }
qctidy-ports = { path = "../ports" }

[features]
default = [
    "codegen-qiskit",
    "codegen-openqasm3",
]
codegen-qiskit = []
codegen-openqasm3 = []

[lints]
workspace = true
