[package]
name = "benchmarks"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
sysinfo = { workspace = true }

[dev-dependencies]
qctidy = { path = "../crates/library" }
criterion = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "performance"
path = "benches/mod.rs"
harness = false
