[package]
name = "qsimplify-qiskit"
version.workspace = true
edition.workspace = true

[lib]
name = "qsimplify_qiskit"
crate-type = ["cdylib"]

[dependencies]
qsimplify = { path = "../library" }
qsimplify-facade = { path = "../facade" }
pyo3 = { workspace = true, features = ["extension-module"] }

[lints]
workspace = true
