[package]
name = "qctidy-qiskit"
description = "Python + Qiskit bindings for QCTidy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories = ["science", "api-bindings"]

[lib]
name = "qctidy_qiskit"
crate-type = ["cdylib"]
doctest = false

[dependencies]
qctidy = { path = "../library" }
qctidy-analyzer = { path = "../analyzer", optional = true }
qctidy-codegen = { path = "../codegen", optional = true }
qctidy-converter = { path = "../converter", optional = true }
qctidy-estimator = { path = "../estimator", optional = true }
qctidy-facade = { path = "../facade" }
qctidy-presenter = { path = "../presenter", optional = true }
qctidy-ports = { path = "../ports" }
faer = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module"] }

[features]
default = [
    "analyzer",
    "codegen-qiskit",
    "codegen-openqasm3",
    "converter-cbor",
    "converter-json",
    "converter-msgpack",
    "converter-xml",
    "estimator",
    "presenter-graphviz",
]
analyzer = [
    "dep:qctidy-analyzer",
    "qctidy-analyzer/analyzer",
    "qctidy-facade/analyzer",
    "qctidy-ports/analyzer",
]
codegen-qiskit = [
    "dep:qctidy-codegen",
    "qctidy-codegen/codegen-qiskit",
    "qctidy-facade/codegen-qiskit",
    "qctidy-ports/codegen-qiskit",
]
codegen-openqasm3 = [
    "dep:qctidy-codegen",
    "qctidy-codegen/codegen-openqasm3",
    "qctidy-facade/codegen-openqasm3",
    "qctidy-ports/codegen-openqasm3",
]
converter-cbor = [
    "dep:qctidy-converter",
    "qctidy-converter/converter-cbor",
    "qctidy-facade/converter-cbor",
    "qctidy-ports/converter-cbor",
]
converter-json = [
    "dep:qctidy-converter",
    "qctidy-converter/converter-json",
    "qctidy-facade/converter-json",
    "qctidy-ports/converter-json",
]
converter-msgpack = [
    "dep:qctidy-converter",
    "qctidy-converter/converter-msgpack",
    "qctidy-facade/converter-msgpack",
    "qctidy-ports/converter-msgpack",
]
converter-xml = [
    "dep:qctidy-converter",
    "qctidy-converter/converter-xml",
    "qctidy-facade/converter-xml",
    "qctidy-ports/converter-xml",
]
estimator = [
    "dep:qctidy-estimator",
    "qctidy-estimator/estimator",
    "qctidy-facade/estimator",
    "qctidy-ports/estimator",
]
presenter-graphviz = [
    "dep:qctidy-presenter",
    "qctidy-facade/presenter-graphviz",
    "qctidy-presenter/presenter-graphviz",
    "qctidy-ports/presenter-graphviz",
]

[lints]
workspace = true
